config/routes.rb
Chatter::Application.routes.draw do

  resources :mentions

  resources :users, :only => [:index]

  resources :followings, :only => [:create, :destroy]
  resources :posts

  get "dashboard/index"

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "devise/registrations#new"
  end

  root :to => 'dashboard#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base

  belongs_to :broadcastable, :polymorphic => true

end

app/models/following.rb
class Following < ActiveRecord::Base

  belongs_to :user
  belongs_to :follower, :class_name => "User"

end

app/models/mention.rb
class Mention < ActiveRecord::Base

  belongs_to :post
  belongs_to :user

end

app/models/mention_observer.rb
class MentionObserver < ActiveRecord::Observer

  observe Mention

  def after_commit(mention)
    NOTIFY_QUEUE.push(:post_id => mention.post_id, :user_id => mention.user_id)
  end

end

app/models/notify.rb
class Notify

  def self.deliver_message_to_user(params)
    post = Post.find(params[:post_id])
    user = User.find(params[:user_id])
    user.channel ||= Channel.new(
      :channel_ident =>
          Digest::SHA1.hexdigest(user.username, user.created_at.to_s))
    PUBNUB.publish({
      'channel' => user.channel.channel_ident,
      'message' => post.to_json(:include => :user)
    })
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  # only allow access to some of the attributes
  attr_accessible :body, :reply_to_id, :ip_address


  # set up the geocoding to locate the tweets
  geocoded_by :ip_address do |obj,results|
    if geo = results.first
      obj.latitude = geo.latitude
      obj.longitude = geo.longitude
      obj.city    = geo.city
      obj.country = geo.country_code
    end
  end
  # and run the geocoding once the object is valid
  after_validation :geocode

  # a post belongs to the user who wrote it
  belongs_to :user

  # and it might have some replies to it
  has_many :replies, :class_name => "Post", :foreign_key => "reply_to_id"
  belongs_to :in_reply_to, :class_name => "Post", :foreign_key => "reply_to_id"

  has_many :mentions
  has_many :mentionings, :through => :mentions, :source => :user

  # make sure that the post has a body, and that it is between
  # 1 and 140 characters long.
  validates :body, :length => 1..140, :presence => true

  has_and_belongs_to_many :tags

  # create a virtual attribute to store the ip_address of
  # the request
  def ip_address
    @ip_address ||= nil
  end

  def ip_address=(ip)
    @ip_address = ip
  end

  serialize :tag_list
  before_save :generate_taglist

  private
  def generate_taglist
    self.tag_list = self.body.scan(/\B#(\w*[A-Za-z0-9_]+\w*)/).flatten
  end

end

app/models/post_observer.rb
class PostObserver < ActiveRecord::Observer
  observe Post

  def after_commit(post)
    puts post
    TAG_PROCESSOR.push(:post_id => post.id)
    users = User.find_all_by_username(detect_usernames(post.body))
    if users
      users.each do |u|
        u.mentioned_ins << post
      end
    end
  end


  private
  def detect_usernames(post)
    post.scan(/\B@(\w*[A-Za-z0-9_]+\w*)/).flatten
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :posts
  has_one :channel, :as => :broadcastable

  def self.process_tags(post_id)
    p = Post.find(post_id)
    p.tag_list.each do |tag|
      t = find_or_initialize_by_content(tag)
      t.posts << p
      t.save
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :description, :username

  validates :username, :presence => true, :uniqueness => true

  has_many :posts

  # code for followers
  has_many :followeds, :class_name => "Following", :foreign_key => "follower_id"
  has_many :follows, :through => :followeds, :source => :user

  has_many :followings
  has_many :followers, :through => :followings

  has_many :mentions
  has_many :mentioned_ins, :through => :mentions, :source => :post

  has_one :channel, :as => :broadcastable

  def timeline
    Post.includes(:user).where(:user_id => Following.where(:follower_id => self.id).pluck(:user_id) << self.id).order("created_at DESC")
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :authenticate_user!

  def index
    @posts = current_user.timeline
  end

end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController

  before_filter :authenticate_user!

  def create
    following = current_user.followeds.build(
                    :user_id => params[:follow])
    if following.save
      flash[:notice] = "Now following."
      redirect_to users_url
    else
      flash[:notice] = "Unable to follow."
      redirect_to users_url
    end
  end

  def destroy
    following = current_user.followeds.find(params[:id])
    following.destroy
    flash[:notice] = "Removed Follow."
    redirect_to users_url
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = current_user.posts.build(params)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    params[:post][:ip_address] = request.ip
    @post = current_user.posts.build(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_url,
                      notice: 'Post was successfully created.' }
        format.json { render json: @post,
                      status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors,
                      status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def index
    @users = User.includes(:followers).
                  where("id != ?", current_user.id).all
    @following = current_user.follows.all
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/mentions_helper.rb
module MentionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<h3>Latest Posts</h3>
<div id="timeline">
<%= render @posts %>
</div>

app/views/followings/create.html.erb
<h1>Followings#create</h1>
<p>Find me in app/views/followings/create.html.erb</p>

app/views/followings/destroy.html.erb
<h1>Followings#destroy</h1>
<p>Find me in app/views/followings/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Chatter</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="#">Chatter Tutorial</a>
          <ul class="nav">
            <li class="active"><a href="/">Home</a></li>
          </ul>
          <% unless current_user %>
            <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => { :class => "pull-right" }) do |f| %>
              <%= f.text_field :username, :class => "input-small", :placeholder => "Username" %>
              <%= f.password_field :password, :class => "input-small", :placeholder => "Password" %>
              <%= button_tag "Sign in", :disable_with => "Please wait...", :class => "btn" %>
            <% end %>
          <% else %>
            <%= form_tag destroy_user_session_path, :method => :delete, :class => "pull-right" do %>
              <%= button_tag "Sign out", :class => "btn" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">

      <div class="content">
        <div class="page-header">
          <% if current_user %>
          <h1>@<%= current_user.username if current_user %> <small>Your Timeline</small></h1>
          <% else %>
          <h1>Please sign in <small>Or <%= link_to "Register", register_path %></h1>
          <% end %>
        </div>
        <div class="row">
          <div class="span10" id="statusUpdater">
          <% if current_user %>
              <div class="clearfix">
              <%= form_for Post.new do |f| %>
                <%= f.text_field :body, :class => "span8", :placeholder => "What are you thinking?" %>
                <%= button_tag "Post", :disable_with => "Please wait...", :class => "span2 btn pull-right" %>
              <% end %>
              </div>
          <% end %>
          <div class="clearfix" id="timelineContainer">
            <%= yield %>
          </div>
          </div>
        </div>

      </div>

      <footer>
        <p>This is a Ruby on Rails tutorial by <%= link_to "@jgwmaxwell", "http://twitter.com/jgwmaxwell" %></p>
      </footer>

    </div> <!-- /container -->
  <% if current_user %>
  <div
      id=pubnub
      pub-key=demo
      sub-key=demo
      ssl=off
      origin=pubsub.pubnub.com
  ></div>
  <script src=http://cdn.pubnub.com/pubnub-3.1.min.js ></script>
  <script>

    function updateTimeline(message) {
        var html = JST['post'](jQuery.parseJSON(message));
        $('#timeline').prepend(html);
    }

    // -------------------
    // LISTEN FOR MESSAGES
    // -------------------
    PUBNUB.subscribe({
        channel  : "<%= Digest::SHA1.hexdigest(current_user.username, current_user.created_at) %>",
        callback : function(message) { updateTimeline(message) }
    })

  </script>
  <% end %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :reply_to_id %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<blockquote>
  <p><%= post.body %></p>
  <small>
  <% if post.user == current_user %>
    You
  <% else %>
    <%= link_to post.user.username, "#" %>
  <% end %>.
  <%= time_ago_in_words(post.created_at) %> ago.
  </small>
</blockquote>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/users/_user.html.erb
<% unless user == current_user %>
<li>
  @<%= user.username %> - following <%= user.follows.count %>, followed by <%= user.followings.count %>
  <% if current_user.follows.include?(user) %>
    <%= link_to "Unfollow", user.followings & current_user.followeds,
                            :method => :delete,
                            :prompt => "Are you sure?" %>
  <% else %>
    <%= link_to "Follow", followings_path(:follow => user.id),
                            :method => :post %>
  <% end %>
</li>
<% end %>

app/views/users/index.html.erb
<h1>Browing Users</h1>
<ul>

  <%= render @users %>

</ul>
<%= link_to "Back Home", root_url %>

app/views/views/dashboard/index.html.erb
<h1>Welcome <%= current_user.username %></h1>
<p><%= current_user.try(:description) %></p>
<ul>
<%= render @posts %>
</ul>
<%= link_to "Create a new post", new_post_path %> |
<%= link_to "Find People", users_path %>

app/views/views/followings/create.html.erb
<h1>Followings#create</h1>
<p>Find me in app/views/followings/create.html.erb</p>

app/views/views/followings/destroy.html.erb
<h1>Followings#destroy</h1>
<p>Find me in app/views/followings/destroy.html.erb</p>

app/views/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatter</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :reply_to_id %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/views/posts/_post.html.erb
<% self_posted = post.user == current_user %>
<li>
  <%= self_posted ? "You" : post.user.username %> said:
  <br />
  <%= post.body %>
  <%= link_to "Reply?", new_post_path(:reply_to_id => post.id) %>
  <% if post.user == current_user %>
  <%= link_to "Delete?", post,
      :method => :delete, :prompt => "Are you sure?" %>
  <% end %>
</li>

app/views/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/views/users/_user.html.erb
<% unless user == current_user %>
<li>
  @<%= user.username %> - following <%= user.follows.count %>, followed by <%= user.followings.count %>
  <% if current_user.follows.include?(user) %>
    <%= link_to "Unfollow", user.followings & current_user.followeds,
                            :method => :delete,
                            :prompt => "Are you sure?" %>
  <% else %>
    <%= link_to "Follow", followings_path(:follow => user.id),
                            :method => :post %>
  <% end %>
</li>
<% end %>

app/views/views/users/index.html.erb
<h1>Browing Users</h1>
<ul>

  <%= render @users %>

</ul>
<%= link_to "Back Home", root_url %>